// @generated
// This file is @generated by prost-build.
/// Swap event collection
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SwapEvents {
    #[prost(message, repeated, tag="1")]
    pub swaps: ::prost::alloc::vec::Vec<AerodromeSwap>,
    #[prost(uint32, tag="2")]
    pub swap_count: u32,
    #[prost(uint64, tag="3")]
    pub total_volume: u64,
}
/// Individual Aerodrome Swap event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AerodromeSwap {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(string, tag="2")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub log_index: u64,
    #[prost(string, tag="4")]
    pub pool_address: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub sender: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub recipient: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub amount0_in: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub amount1_in: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub amount0_out: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub amount1_out: ::prost::alloc::string::String,
    #[prost(uint64, tag="11")]
    pub timestamp: u64,
}
/// Liquidity event collection (Mint/Burn)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LiquidityEvents {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<AerodromeLiquidity>,
    #[prost(uint32, tag="2")]
    pub event_count: u32,
}
/// Individual Aerodrome Liquidity event (Mint or Burn)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AerodromeLiquidity {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(string, tag="2")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub log_index: u64,
    #[prost(string, tag="4")]
    pub pool_address: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub sender: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub recipient: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub amount0: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub amount1: ::prost::alloc::string::String,
    /// "mint" or "burn"
    #[prost(string, tag="9")]
    pub action: ::prost::alloc::string::String,
    #[prost(uint64, tag="10")]
    pub timestamp: u64,
}
/// Sync event collection (reserve updates)
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncEvents {
    #[prost(message, repeated, tag="1")]
    pub events: ::prost::alloc::vec::Vec<SyncEvent>,
    #[prost(uint32, tag="2")]
    pub event_count: u32,
}
/// Individual Sync event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SyncEvent {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(string, tag="2")]
    pub pool_address: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub reserve0: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub reserve1: ::prost::alloc::string::String,
    #[prost(uint64, tag="5")]
    pub timestamp: u64,
}
/// Aerodrome Governance event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AerodromeGovernance {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(string, tag="2")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub log_index: u64,
    #[prost(string, tag="4")]
    pub voter: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub delegate: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub amount: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub timestamp: u64,
    /// "vote" or "delegate"
    #[prost(string, tag="8")]
    pub action: ::prost::alloc::string::String,
}
/// Aerodrome Reward event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AerodromeReward {
    #[prost(uint64, tag="1")]
    pub block_number: u64,
    #[prost(string, tag="2")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(uint64, tag="3")]
    pub log_index: u64,
    #[prost(string, tag="4")]
    pub user: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub amount: ::prost::alloc::string::String,
    #[prost(uint64, tag="7")]
    pub timestamp: u64,
}
// @@protoc_insertion_point(module)
