// @generated
// This file is @generated by prost-build.
/// Aerodrome Swap event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AerodromeSwap {
    #[prost(string, tag="1")]
    pub block_number: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub log_index: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub sender: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub recipient: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub token_in: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub token_out: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub amount_in: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub amount_out: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub price_impact: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub pool_address: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub timestamp: ::prost::alloc::string::String,
}
/// Aerodrome Liquidity event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AerodromeLiquidity {
    #[prost(string, tag="1")]
    pub block_number: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub log_index: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub user: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub pool_address: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub token_a: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub token_b: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub amount_a: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub amount_b: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub liquidity: ::prost::alloc::string::String,
    /// "add" or "remove"
    #[prost(string, tag="11")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub timestamp: ::prost::alloc::string::String,
}
/// Aerodrome Governance event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AerodromeGovernance {
    #[prost(string, tag="1")]
    pub block_number: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub log_index: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub voter: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub delegate: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub timestamp: ::prost::alloc::string::String,
    /// "vote" or "delegate"
    #[prost(string, tag="8")]
    pub action: ::prost::alloc::string::String,
}
/// Aerodrome Reward event
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AerodromeReward {
    #[prost(string, tag="1")]
    pub block_number: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub transaction_hash: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub log_index: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub user: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub token: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub amount: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub timestamp: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
